apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: devsecops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:

      - name: backend

        image: 564362507028.dkr.ecr.ap-south-2.amazonaws.com/backend:7e563ad
        imagePullPolicy: Always


        ports:
        - containerPort: 3500


        env:

        - name: PORT
          value: "3500"


        # MongoDB authentication credentials from Kubernetes Secret
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME


        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD


        # Authenticated MongoDB connection string
        - name: MONGO_CONN_STR
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb.devsecops.svc.cluster.local:27017/devsecops?authSource=admin"


        - name: USE_DB_AUTH
          value: "true"



        readinessProbe:

          httpGet:
            path: /ready
            port: 3500

          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
          successThreshold: 1



        livenessProbe:

          httpGet:
            path: /healthz
            port: 3500

          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1



        startupProbe:

          httpGet:
            path: /started
            port: 3500

          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30



        resources:

          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
