containers:
- name: frontend
  image: 564362507028.dkr.ecr.ap-south-2.amazonaws.com/frontend:v5
  ports:
  - containerPort: 80

  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20

  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
